name: CI Pipeline

on:
  push:
    branches:
      - testing_download
  workflow_dispatch:

jobs:
  build-and-run:
    env:
      CLEARML_API_ACCESS_KEY: ${{ secrets.CLEARML_API_ACCESS_KEY }}
      CLEARML_API_SECRET_KEY: ${{ secrets.CLEARML_API_SECRET_KEY }}
      CLEARML_API_HOST: https://api.clear.ml
    
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # - name: Running the ClearML Queue #TODO
    #   run : |
    #     clearml-agent daemon --queue "default" --detached

    # - name: Run ClearML Pipeline
    #   run: |
    #     python pipeline.py

    - name: Deploy to Streamlit
      run: |
        streamlit run app.py