name: CI Pipeline

on:
  push:
    branches:
      - cicd #TODO
  pull_request:

jobs:
  build-and-run:
    env:
      CLEARML_API_ACCESS_KEY: ${{ secrets.CLEARML_API_ACCESS_KEY }}
      CLEARML_API_SECRET_KEY: ${{ secrets.CLEARML_API_SECRET_KEY }}
      CLEARML_API_HOST: https://api.clear.ml
    
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # - name: Configure ClearML credentials ##
    #   run: |
    #     mkdir -p ~/.clearml
    #     echo "api {
    #       web_server: https://app.clear.ml
    #       api_server: https://api.clear.ml
    #       files_server: https://files.clear.ml
    #       credentials {
    #           access_key: ${{ secrets.CLEARML_API_ACCESS_KEY }}
    #           secret_key: ${{ secrets.CLEARML_API_SECRET_KEY }}
    #       }
    #     }" > ~/.clearml/clearml.conf

    # - name: Set ClearML credentials
    #   run: echo "ClearML environment variables set."
    #   env:
    #     CLEARML_API_ACCESS_KEY: ${{ secrets.CLEARML_API_ACCESS_KEY }}
    #     CLEARML_API_SECRET_KEY: ${{ secrets.CLEARML_API_SECRET_KEY }}
    #     CLEARML_API_HOST: https://app.clear.ml


    - name: Run ClearML Pipeline
      run: |
        python pipeline.py
